version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/audio_discovery"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/audio_discovery/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_audio_discovery"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_audio_discovery/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/audio_discovery/native"
    schedule:
      interval: weekly
